# Generated by Django 5.1.2 on 2024-10-25 09:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guide_fee', models.DecimalField(decimal_places=2, help_text='Fee for the guide', max_digits=10)),
                ('guide_place', models.CharField(help_text='Place where the guide is required', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='trip',
            name='guides',
            field=models.ManyToManyField(blank=True, related_name='trip_related_guides', to='app.guide'),
        ),
    ]
