# Generated by Django 5.1.2 on 2024-10-28 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_otherfee_remove_trip_other_charge_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='destination_place',
        ),
    ]
