# Generated by Django 5.1.2 on 2024-10-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_driver_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='guide_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fee for the guide', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='guide',
            name='guide_place',
            field=models.CharField(blank=True, help_text='Place where the guide is required', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='otherfee',
            name='reason',
            field=models.CharField(blank=True, help_text='Reason for the charge', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='otherfee',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fee for other charges', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='parking',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='toll',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
