# Generated by Django 5.1.2 on 2024-10-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_guide_guide_fee_alter_guide_guide_place_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='guide_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Fee for the guide', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='otherfee',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Fee for other charges', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='parking',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='toll',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
