# Generated by Django 5.1.2 on 2024-10-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_guide_guide_fee_alter_otherfee_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='guide_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Fee for the guide', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='otherfee',
            name='reason',
            field=models.CharField(blank=True, help_text='Description of the other charge', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='otherfee',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Fee for the other charge', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='parking',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='toll',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='advance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='entrance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='parking_fees',
            field=models.ManyToManyField(related_name='trip_related_parking_fees', to='app.parking'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='permit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
