# Generated by Django 5.1.2 on 2024-11-07 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_otherfee_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='parking',
            unique_together={('trip', 'amount')},
        ),
        migrations.AlterUniqueTogether(
            name='toll',
            unique_together={('trip', 'amount')},
        ),
    ]
