# Generated by Django 5.1.2 on 2024-11-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_trip_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='ending_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='starting_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
